package entity;

/**
 *<code> Instruction </code> entity is used for represent and store the commands that Ecbot executes
 * 
 * @author laarguelless
 * @version 0.1
 */
public class Instruction implements InstructionInterface{

    /** Store the command line that Ecbot executes */
    private String command;
    /** Store output generated by the command execution */


    public Instruction() {
        this.command = null; 
    }  
    /**
     * 
     * @return Command line 
     */
    public String getCommand() {
        return command;
    }

    /**
     *
     * @param command
     */
    public void setCommand(String command) {
        this.command = command+"\n";
    }

    /**
     *
     * @return output generated by command execution
     */
    

}
